# Generated by Django 2.2.6 on 2022-04-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220415_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='subsription',
        ),
    ]
