# Generated by Django 2.2.6 on 2022-04-15 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220416_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
